name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        gRPC_version: [x86-windows-static, x86-windows, x64-windows-static, x64-windows]
      fail-fast: false
      
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Update vcpkg
      run: vcpkg update
      
    - name: Install version gRPC ${{ matrix.gRPC_version }}
      run: vcpkg install grpc:${{ matrix.gRPC_version }}
      
    - name: Copy installed libraries
      shell: bash
      run: |
        mkdir ./artifacts
        cd artifacts
        mkdir ./${{ matrix.gRPC_version }}
        cp -rv $(VCPKG_INSTALLATION_ROOT)/installed/${{ matrix.gRPC_version }} ./${{ matrix.gRPC_version }}
      
    - name: Create 7z Release
      uses: DuckSoft/create-7z-action@v1.0
      with:
        pathSource: ./artifacts
        pathTarget: ./artifacts-${{ matrix.gRPC_version }}.7z
    - name: Uploading artifact
      uses: actions/upload-artifact@master
      with:
        name: artifacts-${{ github.sha }}-${{ matrix.gRPC_version }}.7z
        path: artifacts.7z
